name: ba3_bs
description: "BA3 Business Solutions App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.7.0
  pluto_grid: ^8.0.0
  fluttertoast: ^8.2.10
  intl: 0.19.0
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.0
  dartz: ^0.10.1
  nfc_manager: ^3.5.0
  #  window_manager: ^0.4.3
  native_dialog_plus: ^1.0.9
  flutter_platform_alert: ^0.6.1
  syncfusion_flutter_datagrid: ^28.1.38
  syncfusion_flutter_datepicker: ^28.1.38
  flutter_material_color_picker: ^1.2.0
  tab_container: ^3.5.3
  math_expressions: ^2.6.0
  image: ^4.3.0
  print_bluetooth_thermal: ^1.1.4
  esc_pos_utils_plus: ^2.0.4
  http: ^1.2.2
  path_provider: ^2.1.5
  mailer: ^6.3.0
  qr_flutter: ^4.1.0
  pdf: ^3.11.1
  equatable: ^2.0.7
  mocktail: ^1.0.4
  geolocator: ^13.0.2
  shared_preferences: ^2.3.5
  day_night_time_picker: ^1.3.1
  file_picker: ^9.0.2
  xml: ^6.5.0
  logger: ^2.5.0
  syncfusion_flutter_gauges: ^28.1.38
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.8.0
  multi_select_flutter: ^4.1.3
  shimmer: ^3.0.0
  pool: ^1.5.1
  dropdown_button2: ^2.3.9
#  flutter_thermal_printer: ^1.1.0
#  flutter_local_notifications: ^18.0.1
#  timezone: ^0.10.0
#  printing: ^5.14.2
#  flutter_usb_printer: ^0.1.0+1
#  ffi: ^2.0.1
#  win32: ^5.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/flags/
    - assets/translations/translations.json


  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/notoSansArabic/NotoSansArabic-Regular.ttf
        - asset: assets/fonts/notoSansArabic/NotoSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/notoSansArabic/NotoSansArabic-Bold.ttf
          weight: 700

    - family: Almarai
      fonts:
        - asset: assets/fonts/almarai/AlmaraiRegular.ttf