name: ba3_bs
description: "BA3 Business Solutions App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.7.0
  pluto_grid: ^8.0.0
  fluttertoast: ^8.2.8
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.0
  dartz: ^0.10.1
  nfc_manager: ^3.5.0
  window_manager: ^0.4.2
  native_dialog_plus: ^1.0.7
  flutter_platform_alert: ^0.6.1
  syncfusion_flutter_datagrid: ^27.1.55
  syncfusion_flutter_datepicker: ^27.1.56
  flutter_material_color_picker: ^1.2.0
  tab_container: ^3.5.3
  math_expressions: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
