// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7gnUmnTVvPbNIZjSwXNIqq5FdyF_mFGE',
    appId: '1:307353344258:web:c3d6b71f8ee49afdf78a1b',
    messagingSenderId: '307353344258',
    projectId: 'ba3-bs',
    authDomain: 'ba3-bs.firebaseapp.com',
    storageBucket: 'ba3-bs.firebasestorage.app',
    measurementId: 'G-916FSY646M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO5jNanpbBzbnSJU8oavQzJMN2E71p-JI',
    appId: '1:307353344258:android:861d31495b29e4b3f78a1b',
    messagingSenderId: '307353344258',
    projectId: 'ba3-bs',
    storageBucket: 'ba3-bs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXyLX6KNjdLQQmDDd3YCMbwOn5iDsaWjc',
    appId: '1:307353344258:ios:c1a563e9afc6174ff78a1b',
    messagingSenderId: '307353344258',
    projectId: 'ba3-bs',
    storageBucket: 'ba3-bs.firebasestorage.app',
    iosBundleId: 'com.ba3bs.ba3Bs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXyLX6KNjdLQQmDDd3YCMbwOn5iDsaWjc',
    appId: '1:307353344258:ios:c1a563e9afc6174ff78a1b',
    messagingSenderId: '307353344258',
    projectId: 'ba3-bs',
    storageBucket: 'ba3-bs.firebasestorage.app',
    iosBundleId: 'com.ba3bs.ba3Bs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7gnUmnTVvPbNIZjSwXNIqq5FdyF_mFGE',
    appId: '1:307353344258:web:237117f44751a6d4f78a1b',
    messagingSenderId: '307353344258',
    projectId: 'ba3-bs',
    authDomain: 'ba3-bs.firebaseapp.com',
    storageBucket: 'ba3-bs.firebasestorage.app',
    measurementId: 'G-BR6KLWJZ9B',
  );

}